Affichage d'information
<div class="hero-unit"><h1>Réseau Sociaux + Check <small><?php echo $this->message; ?></small></h1></div>
<ul class="nav nav-list">
              <li class="nav-header">Menu de test pour Check</li>
              <li><a href="sociaux-check-id">Check Id</a></li>
              <li><a href="sociaux-check-list">Check List</a></li>
              <li><a href="sociaux-check">Check</a></li>
              <li><a href="sociaux">Normale</a></li>
              </ul>