Affichage d'information
<div class="hero-unit">
  <h1>Réseau Sociaux + Check <small><?php echo $this->message; ?></small></h1>
</div>
<div class="contenair">
Eviter les ( # , &, ~ )
</div>
<ul class="nav nav-list">
  <li class="nav-header">Menu de test pour Check</li>
  <li><a href="sociaux-check-id">Check Id</a></li>
  <li><a href="sociaux-check-list">Check List</a></li>
  <li><a href="sociaux-check">Check</a></li>
  <li><a href="sociaux">Normale</a></li>
</ul>

<ul class="nav nav-list">
  <li class="nav-header">Menu de test pour Check</li>
  <li><a href="sociaux-check-id~4657461">Chiffres</a></li>
  <li><a href="sociaux-check-id~df4545fd">Chiffres Lettres</a></li>
  <li><a href="sociaux-check-id~RA_sdsqdqf">Underscore</a></li>
  <li><a href="sociaux-check-id~RA_4546-JDJKH">-</a></li>
</ul>
